metadata:
  name: beerdar
  versionScheme: semver

build:
  image: alpine:latest
  timeoutSeconds: 600

artifacts:
  - name: pubfinder-api
    pattern: "backend/Dockerfile"
    type: "docker-image"

  - name: pubfinder-ui
    pattern: "frontend/Dockerfile"
    type: "docker-image"
